# Generated by Django 5.2.10 on 2026-01-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(upload_to='content/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_display_duration', models.PositiveIntegerField(default=30, verbose_name='Link Display Duration (seconds)')),
                ('scholarship_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('masters', "Master's"), ('phd', 'PhD'), ('postdoc', 'Postdoctoral'), ('research', 'Research')], max_length=20, verbose_name='Type')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('university', models.CharField(max_length=200, verbose_name='University/Institution')),
                ('deadline', models.DateField(verbose_name='Application Deadline')),
                ('funding_amount', models.TextField(blank=True, verbose_name='Funding Amount')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('application_process', models.TextField(verbose_name='Application Process')),
                ('official_link', models.URLField(verbose_name='Official Link')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Scholarship')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tip Title')),
                ('content', models.TextField(verbose_name='Tip Content')),
                ('order', models.IntegerField(default=0)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
