# Generated by Django 5.2.10 on 2026-01-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(upload_to='content/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_display_duration', models.PositiveIntegerField(default=30, verbose_name='Link Display Duration (seconds)')),
                ('book_type', models.CharField(choices=[('book', 'Book'), ('summary', 'Summary'), ('notes', 'Study Notes')], default='book', max_length=20, verbose_name='Type')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Publisher')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('download_link', models.URLField(blank=True, verbose_name='Download Link')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='File')),
                ('preview_pages', models.PositiveIntegerField(default=10, verbose_name='Preview Pages')),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Download History',
            },
        ),
    ]
