# Generated by Django 5.2.10 on 2026-01-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
