# Generated by Django 5.2.10 on 2026-01-12 08:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('template', models.CharField(choices=[('default', 'Default Template'), ('fullwidth', 'Full Width'), ('sidebar_left', 'Sidebar Left'), ('sidebar_right', 'Sidebar Right')], default='default', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private')], default='draft', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
