# Generated by Django 5.2.10 on 2026-01-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
