# Generated by Django 5.2.10 on 2026-01-13 10:31

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(blank=True, help_text='Recommended size: 1200x630 pixels', null=True, upload_to='pages/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Recommended size: 300x200 pixels', null=True, upload_to='pages/thumbnails/%Y/%m/%d/')),
                ('template', models.CharField(choices=[('default', 'Default Template'), ('fullwidth', 'Full Width'), ('sidebar_left', 'Sidebar Left'), ('sidebar_right', 'Sidebar Right'), ('contact', 'Contact Page'), ('landing', 'Landing Page')], default='default', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, max_length=300, verbose_name='SEO Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO Keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('allow_comments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Expire Date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.pagecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Comment',
                'verbose_name_plural': 'Page Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Rating',
                'verbose_name_plural': 'Page Ratings',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'publish_date'], name='pages_page_status_9c582b_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='pages_page_slug_3e99a9_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['created_at'], name='pages_page_created_aae7e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagerating',
            unique_together={('page', 'user')},
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page', 'created_at'], name='pages_pagev_page_id_f30d1c_idx'),
        ),
    ]
