# Generated by Django 5.2.10 on 2026-01-13 17:46

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط')),
                ('content', ckeditor.fields.RichTextField(verbose_name='المحتوى')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='المقتطف')),
                ('featured_image', models.ImageField(upload_to='blog/featured/%Y/%m/', verbose_name='الصورة الرئيسية')),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/thumbnails/%Y/%m/', verbose_name='الصورة المصغرة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('private', 'خاص'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='المشاهدات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, max_length=300, verbose_name='وصف SEO')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='كلمات مفتاحية SEO')),
                ('canonical_url', models.URLField(blank=True, verbose_name='رابط Canonical')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
