# Generated by Django 5.2.10 on 2026-01-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Placement Name')),
                ('code', models.SlugField(unique=True)),
                ('placement_type', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('between_posts', 'Between Posts'), ('popup', 'Popup'), ('in_content', 'In Content')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(default=300)),
                ('height', models.PositiveIntegerField(default=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad Title')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Image'), ('text', 'Text Ad'), ('html', 'HTML Code'), ('video', 'Video Ad')], default='banner', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('text_content', models.TextField(blank=True)),
                ('html_code', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('link', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.adplacement')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
